In [3]:
import numpy as np
a = np.arange(6)
print(a)
b = np.arange(12).reshape(4,3)
print(b)
c=  np.arange(24).reshape(2,3,4)
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A*B) #elementwise product
print(A@B) #matrix product
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [5]:
import math
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, math.pi, 3)
rg = np.random.default_rng(1) 
c = rg.random((2,3))
print(c)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [6]:
a = np.arange(10)**3
print(a)
print(a[2:5])
a[0:6:2] = 1000
print(a)
b = np.array([1,3,4,5])
b = b[::-1]
print(b)

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[5 4 3 1]


In [7]:
a = np.floor(10 * rg.random((3, 4)))